In [ ]:
##00

print("Hello")

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
## intro to tensors

### creating tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

## get tensor back as python list
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

matrix.shape

In [ ]:
matrix[:,0]

tensor([7, 9])

In [ ]:
matrix[0,0]

tensor(7)

##TENSOR

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

`dim = 0 [1,2,3][3,6,9][2,4,5]
dim = 1 [],[],[]
dim = 2 [.,.,.]`

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0,0,2]

tensor(3)

In [ ]:
##random tensors

## why random tensors?

rando = torch.rand(3,4)
rando

tensor([[0.3784, 0.1186, 0.4627, 0.0727],
        [0.3501, 0.5678, 0.0199, 0.2033],
        [0.8497, 0.5211, 0.7965, 0.8532]])

In [ ]:
rando[1,2]

tensor(0.0199)

In [ ]:
rando.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
## Zeroes and Ones
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*rando

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype #default data type

torch.float32

In [ ]:
### creat a range odf tensors and tensors like

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
## creating tensors like
ten_zeroes_like = torch.zeros_like(input=one_to_ten)
ten_zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##17 Tensor Datatype

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device='cpu', #which memeory is the tensor on?
                               requires_grad=False)# to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
## getting inf from tensors

##tensor.dtype
##tensor.shape
##tensor.device


In [ ]:
some_tensor = torch.rand(3,4,dtype=torch.float16)
some_tensor

tensor([[0.3794, 0.7500, 0.0537, 0.7686],
        [0.8091, 0.8521, 0.7998, 0.5059],
        [0.6113, 0.3511, 0.0151, 0.7012]], dtype=torch.float16)

In [ ]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
some_tensor.device, some_tensor.dtype

(device(type='cpu'), torch.float16)

In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor = tensor*10
tensor

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([ 0, 10, 20])

In [ ]:
## pytorch inbuilt
torch.mul(tensor,10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor, 20)

tensor([30, 40, 50])

In [ ]:
##multiplication matrix
## element wise multiplication
## matrx multiplication
tensor = torch.tensor([[1,1,1],[1,1,1]])
tensor2 = torch.tensor([[2,3],[3,4],[4,5]])
torch.matmul(tensor2,tensor)

tensor([[5, 5, 5],
        [7, 7, 7],
        [9, 9, 9]])

In [ ]:
# shapes for matrix mult

In [ ]:
tensor_a = torch.tensor([[1,2],[3,4],[5,6]])

tensor_b = torch.tensor([[7,10],[8,11],[9,12]])

torch.mm(tensor_b.T,tensor_a)

tensor([[ 76, 100],
        [103, 136]])

In [ ]:
 #finding the min, max, mean of the tensor

In [ ]:
x = torch.arange(1,100,10)
torch.mean(x.type(torch.float32)), x.min(), x.max()


(tensor(46.), tensor(1), tensor(91))

In [ ]:
x.type(torch.float32).mean()

tensor(46.)

In [ ]:
torch.sum(x)

tensor(460)

In [ ]:
x.argmax() ## position that has max value
x.argmin() ## position with min value

tensor(0)

In [ ]:
x[9]

tensor(91)

In [ ]:
## reshaping, stacking, squeezing and unsqueezing and permute

In [ ]:
x = torch.arange(1.,10.)

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
## squeeze and unsqueeze

In [ ]:
 # squeeze = removes all single dimensions

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeeze = x_reshaped.squeeze()

In [ ]:
x_unsqueeze = x_squeeze.unsqueeze(dim = 0)

In [ ]:
x_unsqueeze.shape

torch.Size([1, 9])

In [ ]:
# permute = used moslty with images
x_orginal = torch.rand(size=(224,224,3))

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_orginal.permute(2,0,1) # shifts axis 0 to 1 , 1 > 2 and 2 to 0
x_orginal.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
## indexing

#indexing iwth numpy and pytorch is same

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#numpy is a popular computing library

In [ ]:
#torch.from_numpy(ndarray)
#torch.Tensor.numpy()

In [ ]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#but why float 64

In [ ]:
#change values of array

In [ ]:
array = array + 1
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
##reproductibilty (trying to make random out of random)
torch.rand(3,3)

## to reduce the randomess in a neural networks and putorch comes with
## the concept of a random seed

tensor([[0.6360, 0.5129, 0.6423],
        [0.6016, 0.9508, 0.0684],
        [0.4363, 0.4390, 0.8084]])

In [ ]:
random_tesnor_a = torch.rand(3,4)
random_tesnor_b = torch.rand(3,4)

print(random_tesnor_a)
print(random_tesnor_b)
print(random_tesnor_a == random_tesnor_b)

tensor([[0.3251, 0.7321, 0.6160, 0.1507],
        [0.5651, 0.0771, 0.2689, 0.4139],
        [0.7548, 0.9680, 0.2797, 0.9623]])
tensor([[0.6154, 0.5464, 0.9503, 0.6893],
        [0.5680, 0.6759, 0.5714, 0.6831],
        [0.6977, 0.5922, 0.7945, 0.7120]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random reproducatble tensors

In [ ]:
#set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tesnor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tesnor_d = torch.rand(3,4)

print(random_tesnor_c)
print(random_tesnor_d)
print(random_tesnor_c == random_tesnor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
## running tensors and pytorch objects on GPU
"""
  getting a gpu
  1. google collab gpu
  2. use your own gpu
  3. use cloud computing - GCP, AWS, Azure
"""

'\n  getting a gpu\n  1. google collab gpu\n  2. use your own gpu\n  3. use cloud computing - GCP, AWS, Azure\n'

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
torch.cuda.is_available()

False

In [ ]:
## setup device agnostic code

In [ ]:
device = 'cuda' if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count()

0

In [ ]:
#python set agnostic codee

# putting the code on gpu makes it faster


In [ ]:
# cant covert tensor on gpu to numpy

In [ ]:
"""import torch
print(torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"
##gpu great at numerical calc

tensor = torch.tensor([1,2,3])
## move tensor to gpu if available

tensor_gpu = tensor.to(device)
print(tensor_gpu, tensor_gpu.device)

tensor_back_on_cpu = tensor_gpu.cpu().numpy()
print(tensor_back_on_cpu)"""

'import torch\nprint(torch.cuda.is_available())\ndevice = "cuda" if torch.cuda.is_available() else "cpu"\n##gpu great at numerical calc\n\ntensor = torch.tensor([1,2,3])\n## move tensor to gpu if available\n\ntensor_gpu = tensor.to(device)\nprint(tensor_gpu, tensor_gpu.device)\n\ntensor_back_on_cpu = tensor_gpu.cpu().numpy()\nprint(tensor_back_on_cpu)'